name: Create RForge Draft Release

on:
  # Runs on pushes targeting the `main` branch
  # when src/** is updated on the main branch
  push:
    branches: [main]
    paths:
      - 'src/**'
  # Allows for running manually from Actions tab
  workflow_dispatch:
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: blazor-rforge
  cancel-in-progress: false

defaults:
  run:
    working-directory: src/RForge

jobs:
  version-and-release:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      actions: write
      attestations: write

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
    
      # Setup Env
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.0.x'

        # Determine the next version. (rc is added based on GitVersion.yml settings)
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with: 
          useConfigFile: true
      
      - name: Build with dotnet
        run: dotnet build --configuration Release
      
      - name: Set up GitHub Nuget Repository
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Rumhyek/index.json"
        
      # Pack all packages at the given version
      - name: Package Pack
        run: dotnet pack --output ${{env.DOTNET_ROOT}}/artifacts --configuration Release -p:Version=${{ steps.gitversion.outputs.SemVer }}
      
      # Publish the packages to github under RForge
      - name: Publish Packages (Github)
        run: dotnet nuget push ${{env.DOTNET_ROOT}}/artifacts/*.nupkg --source github --skip-duplicate
        
      # Publish the packages to nuget under RForge
      - name: Publish Packages (Nuget)
        run: dotnet nuget push ${{env.DOTNET_ROOT}}/artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate

      # Create the release as draft so I can add more details if needed.
      - name: Github Release
        run: gh release create v${{ steps.version.outputs.MajorMinorPatch }} --generate-notes --draft
        env:
          GH_TOKEN: ${{ github.token }}