# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Publish new RForge Package

on:
  # Runs on pushes targeting the `main` branch
  # when src/** is updated on the main branch
  push:
    branches: [main]
    paths:
      - 'src/**'
  release:
    types:
      - published
  # Allows for running manually from Actions tab
  workflow_dispatch:
  
defaults:
  run:
    working-directory: src/RForge

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      actions: write
      attestations: write

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
    
      # Setup Env
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Build with dotnet
        run: dotnet build --configuration Release
      
      - name: Set up GitHub Nuget Repository
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Rumhyek/index.json"
        
      # Pack all packages at the given version
      - name: Package Pack
        run: dotnet pack --output ${{env.DOTNET_ROOT}}/artifacts --configuration Release -p:Version=0.9.0
      
      # Publish the packages to github under RForge
      - name: Publish Packages to GitHub
        run: dotnet nuget push ${{env.DOTNET_ROOT}}/artifacts/*.nupkg --source github --skip-duplicate
      
      # Publish the packages to nuget under RForge
      - name: Publish Packages (Nuget)
        run: dotnet nuget push ${{env.DOTNET_ROOT}}/artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
